---

- name: NVM | main | Install Required Packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: "{{ required_packages }}"

- include: nvm.yml

- include: node.yml

- include: pkgs.yml
  when: "{{ nvm_npm_pkgs | length }} > 0"

# needed in order to preserve idempotency due to globally installed packages
- include: permission.yml
